#pragma once

// Strings
#define ID_MINESWEEPER_CLASSNAME 1
#define ID_ERROR 3
#define ID_TIMER_ERROR 4
#define ID_OUT_OF_MEM 5
#define ID_ERR_MSG_D 6
#define ID_SECONDS_LEFT 7
#define ID_ANONYMOUS 8
#define ID_FASTEST_TIME_BEGINNER_MSG 9
#define ID_FASTEST_TIME_INTERMEDIATE_MSG 10
#define ID_FASTEST_TIME_EXPERT_MSG 11
#define ID_MINESWEEPER2 12
#define ID_CREDITS 13

// Menu Object
#define ID_MENU 500

// Accelerators (Shortcuts)
#define ID_ACCELERATORS 501

// Icon Group
#define ID_ICON_GROUP 100

// Menu Items
#define ID_MENUITEM_NEWGAME 510
#define ID_MENUITEM_EXIT 512
#define ID_MENUITEM_BEGINNER 521
#define ID_MENUITEM_INTERMEDIATE 522
#define ID_MENUITEM_EXPERT 523
#define ID_MENUITEM_CUSTOM 524
#define ID_MENUITEM_SOUND 526
#define ID_MENUITEM_MARKS 527
#define ID_MENUITEM_BEST_TIMES 528
#define ID_MENUITEM_COLOR 529

// Menu Items - Help
#define ID_MENUITEM_CONTENTS 590
#define ID_MENUITEM_SEARCH_FOR_HELP 591
#define ID_MENUITEM_USING_HELP 592
#define ID_MENUITEM_ABOUT 593


// Sounds
#define ID_SOUND_TICK 432
#define ID_SOUND_WIN 433
#define ID_SOUND_LOSE 434


// Dialogs 
// Save Winner Name Dialog
#define ID_DIALOG_SAVE_NAME 600
#define ID_DIALOG_SAVE_NAME_CONTROL_MSG 601
#define ID_DIALOG_SAVE_NAME_CONTROL_NAME 602

// Show Fastest Minesweepers Dialog
#define ID_DIALOG_WINNERS 700
#define ID_DIALOG_WINNERS_TIME_BEGINNER 0x2BD
#define ID_DIALOG_WINNERS_NAME_BEGINNER 0x2BE
#define ID_DIALOG_WINNERS_TIME_INTERMIDIATE 0x2BF
#define ID_DIALOG_WINNERS_NAME_INTERMIDIATE 0x2C0
#define ID_DIALOG_WINNERS_TIME_EXPERT 0x2C1
#define ID_DIALOG_WINNERS_NAME_EXPERT 0x2C2
#define ID_DIALOG_WINNERS_BTN_RESET_SCORES 707

// Custom Field Dialog
#define ID_DIALOG_CUSTOM_FIELD 80
#define ID_DIALOG_CUSTOM_FIELD_OK 1
#define ID_DIALOG_CUSTOM_FIELD_CANCEL 2
#define ID_DIALOG_CUSTOM_FIELD_HEIGHT 141
#define ID_DIALOG_CUSTOM_FIELD_WIDTH 142
#define ID_DIALOG_CUSTOM_FIELD_MINES 143
#define ID_DIALOG_CUSTOM_FIELD_HEIGHT_LABEL 112
#define ID_DIALOG_CUSTOM_FIELD_WIDTH_LABEL 113
#define ID_DIALOG_CUSTOM_FIELD_MINES_LABEL 111


// Bitmaps
#define ID_BITMAP_BLOCK 410
#define ID_BITMAP_NUMBERS 420
#define ID_BITMAP_SMILES 430